prepare:
  stage: build
  image: python:3.5
  script:
  - pip install -r _build/requirements.txt
  - python -m unittest discover -s _build/
  - python _build/build.py
  - python _build/generate_map_img.py
  artifacts:
    paths:
    - _data/stats.json
    - img/googlemap.png

pages:
  stage: deploy
  image: ruby:2.3
  script:
  - gem install bundler
  - bundle install
  - jekyll build -d public
  artifacts:
    paths:
    - public
  only:
  - master
  dependencies:
  - prepare