build-stats:
  stage: build
  image: python:3.5
  script:
  - pip install -r _build/requirements.txt
  - python _build/build.py
  artifacts:
    paths:
    - _data/nn_out.csv

pages:
  stage: deploy
  image: ruby:2.3
  script:
  - bundle install
  - jekyll build -d public
  artifacts:
    paths:
    - public
  only:
  - master
  dependencies:
  - build-stats