# Site Settings
locale:             'en'
title:              'App Trail'
tagline:            'Getting lost in the woods with friends!'
description:        'Getting lost in the woods with friends!'
theme:              minimal-mistakes-jekyll
include:            
  - "_pages"
  - "assets"
exclude:
  - Gemfile
  - Gemfile.lock

# Analytics
analytics:
  provider:             "google"
  google:
    tracking_id:        "UA-91926226-1"

# About/contact
author:
  name:             Daniel Dixon
  email:            'dnldxn@gmail.com'

# Custom vars
version:             0.0.10

# Outputting
permalink:          pretty
paginate:           5                               # amount of posts to show
timezone:           'America/Los_Angeles'           # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones

gitlab-letsencrypt:
  # Gitlab settings:
  personal_access_token: 'XzavcLkj8sNLeVBbz82D'       # Gotten from the step above ^^
  gitlab_repo:           'dnldxn/dnldxn.gitlab.io'    # Namespaced repository identifier

  # Domain settings:
  email:                 'dnldxn@gmail.com.com'       # Let's Encrypt email address
  domain:                'lostwithdan.com'            # Domain that the cert will be issued for

  # Jekyll settings:
  base_path:        './'                              # Where you want the file to go
  pretty_url:       true                              # Add a "/" on the end of the URL... set to `true` if you use permalink_style: pretty
  filename:         'letsencrypt.html'                # What to call the generated challenge file

  # Delay settings:
  initial_delay:    240                               # How long to wait for Gitlab CI to push your changes before it starts checking
  delay_time:       15                                # How long to wait between each check once it starts looking for the file

# Enable Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

# Sass/SCSS
sass:
  sass_dir:         _sass
  style:            compressed

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: # true
      share: true
      related: true
