# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               'App Trail'
tagline:             'A Jekyll theme'
description:         'A reserved Jekyll theme that places the utmost gravity on content with a hidden drawer.</a>.'
paginate:            5

# About/contact
author:
  name:              Daniel Dixon
  email:             @gmail.com

# Custom vars
version:             0.0.1
